### ISSUE TITLE
Latest Chrome cookie not loading

### ISSUE THREAD

**Issue by 2naive** [DvaMishkiLapa/VKArchiveDownloader#21]
```
 CRITICAL | Traceback (most recent call last):
  File "main.py", line 321, in <module>
  File "asyncio\runners.py", line 44, in run
  File "asyncio\base_events.py", line 649, in run_until_complete
  File "main.py", line 211, in main
  File "browser_cookie3\__init__.py", line 897, in load
  File "browser_cookie3\__init__.py", line 840, in chrome
  File "browser_cookie3\__init__.py", line 430, in __init__
  File "browser_cookie3\__init__.py", line 229, in __init__
  File "browser_cookie3\__init__.py", line 290, in __add_key_and_cookie_file
  File "browser_cookie3\__init__.py", line 45, in create_local_copy
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\user\\AppData\\Roaming\\..\\Local\\Google\\Chrome\\User Data\\Default\\Network\\Cookies'
```

Caused by: https://github.com/borisbabic/browser_cookie3/issues/180

**Comment by DvaMishkiLapa** [comment]
The guys in this repository seem to have found a temporary solution. I have encountered this problem too, it occurs if Google Chrome is open while the script is running. As an option, you can close it. Or you can open it when the script has started the download process (after receiving all links from the archive).

Alternatively, do not use cookies by specifying the appropriate flag in the config file.

**Comment by 2naive** [comment]
https://github.com/borisbabic/browser_cookie3/issues/180#issuecomment-1587691954
