### ISSUE TITLE
Special chars in folder names

### ISSUE THREAD

**Issue by 2naive** [DvaMishkiLapa/VKArchiveDownloader#22]
```
2023-09-23 01:10:14 | CRITICAL | Traceback (most recent call last):
  File "main.py", line 321, in <module>
  File "asyncio\runners.py", line 44, in run
  File "asyncio\base_events.py", line 649, in run_until_complete
  File "main.py", line 297, in main
  File "main.py", line 120, in profile_photos_handler
  File "tools.py", line 24, in create_folder
  File "os.py", line 225, in makedirs
OSError: [WinError 123] Синтаксическая ошибка в имени файла, имени папки или метке тома: 'output\\photos/photo-albums\\25/06 02:00-05:00'
```

**Comment by DvaMishkiLapa** [comment]
You don't have to translate everything into Russian :)

Could you give me the full log file and config file of your scan?

As I understand it was a Windows system?

**Comment by DvaMishkiLapa** [comment]
Anyway, I think I've found the source of the problem. I replaced all the specials in the folder names with `_` (https://github.com/DvaMishkiLapa/VKArchiveDownloader/commit/83b73002e323f27bd4491a5f6de66751d7f50c9f).

Try the latest version.
